spring.application.name=understand-servlet-crud-list-collection
# Config Servlet viewer , in this case i use java code instead
#spring.mvc.view.prefix= /WEB-INF/jsp/
#spring.mvc.view.suffix= .jsp
logging.level.root[0]=info
logging.level.root[1]=warn
