spring.application.name=understand-servlet-crud-list-collection
# Config Servlet viewer this case i use java code instead # set controller
#spring.mvc.view.prefix= /WEB-INF/jsp/
#spring.mvc.view.suffix= .jsp
